spring:
  profiles:
    active: local

---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    username: root
    password: strongpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: mysql